Assignments
pratik29046/pascal pull request #1
Opened 2022-04-18 13:12 UTC by pratik29046

2022-04-18 13:13 UTC, Shashank-Shastri approved these changes

2022-04-18 13:15 UTC, Shashank-Shastri requested changes
Test

2022-04-18 13:16 UTC, Shashank-Shastri approved these changes

2022-04-18 13:17 UTC, merged

2022-04-22 07:39 UTC, pratik29046 commented on email validation/email_u.pas
> + if trim(EDE_Input.Text)='' then      //trim method used
done